dist: trusty
language: node_js
node_js:
- '10'
- '8'
before_install:
# We want a dump of the travis variables for debugging purposes.
- env | grep TRAVIS_
- sudo apt-get update -qq
- sudo apt-get install -y xsltproc jing
script: gulp test
branches:
  except:
  - master
